// Dungeon Addons manifest (JS). See ダンジョン生成追加API書.md
// You can add more entries here or replace with your own.
window.DUNGEONTYPE_MANIFEST = [
  { id: 'lava_pack',      name: 'Lava Pack',      entry: 'dungeontypes/lava_caves.js',      version: '1.0.0', author: 'builtin-sample' },
  { id: 'ring_city_pack', name: 'Ring City Pack', entry: 'dungeontypes/ring_city.js',       version: '1.0.0', author: 'builtin-sample' },
  { id: 'grand_medieval_city_pack', name: 'Grand Medieval City Pack', entry: 'dungeontypes/grand_medieval_city.js', version: '1.1.0', author: 'builtin-sample' },
  { id: 'medieval_stronghold_pack', name: 'Medieval Stronghold Pack', entry: 'dungeontypes/medieval_stronghold.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'icy_caverns_pack', name: 'Icy Caverns Pack', entry: 'dungeontypes/icy_caverns.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'serpentine_pack', name: 'Serpentine River Pack', entry: 'dungeontypes/serpentine_river.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'ruins_pack',     name: 'Overgrown Ruins Pack', entry: 'dungeontypes/overgrown_ruins.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'geometric_pack', name: 'Geometric Structures Pack', entry: 'dungeontypes/geometric_structures.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'corridor_pack',  name: 'Corridor Patterns Pack', entry: 'dungeontypes/corridor_patterns.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'skyward_pack',   name: 'Skyward Bastions Pack', entry: 'dungeontypes/skyward_bastions.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'fungal_pack',    name: 'Fungal Bloom Pack', entry: 'dungeontypes/fungal_bloom.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'clockwork_pack', name: 'Clockwork Labyrinth Pack', entry: 'dungeontypes/clockwork_labyrinth.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'tidal_pack',     name: 'Tidal Catacombs Pack', entry: 'dungeontypes/tidal_catacombs.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'prison_pack',    name: 'Underground Prison Pack', entry: 'dungeontypes/underground_prison.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'forest_pack',    name: 'Verdant Forest Pack', entry: 'dungeontypes/forest_caverns.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'shore_pack',     name: 'Sunlit Shore Pack', entry: 'dungeontypes/beach_shore.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'desert_pack',    name: 'Scorched Desert Pack', entry: 'dungeontypes/desert_field.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'bog_pack',       name: 'Toxic Boglands Pack', entry: 'dungeontypes/poison_bogs.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'bomb_pack',      name: 'Bomb Hazard Pack', entry: 'dungeontypes/bomb_fields.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'shadowed_caverns_pack', name: 'Shadowed Caverns Pack', entry: 'dungeontypes/dark_caverns.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'sandstorm_dunes_pack', name: 'Sandstorm Dunes Pack', entry: 'dungeontypes/sandstorm_desert.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'sun_kings_necropolis_pack', name: 'Sun-Kings Necropolis Pack', entry: 'dungeontypes/egyptian_sun_kings.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'irradiated_plains_pack', name: 'Irradiated Plains Pack', entry: 'dungeontypes/irradiated_plains.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'conveyor_foundry_pack', name: 'Conveyor Foundry Pack', entry: 'dungeontypes/conveyor_foundry.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'oneway_labyrinth_pack', name: 'One-Way Labyrinth Pack', entry: 'dungeontypes/oneway_labyrinth.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'axis_gallery_pack', name: 'Axis Gallery Pack', entry: 'dungeontypes/axis_gallery.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'fantasical-sci-fi-dream-pack', name: 'ファンタジカルと近未来をテーマにした夢の世界パック', entry: 'dungeontypes/FantasicalAndSci-fiAndDremerPack.js', version: '3.0.0', author: 'builtin-sample' },
  { id: 'luminescent_glade_pack', name: 'Luminescent Glade Pack', entry: 'dungeontypes/luminescent_glade.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'coral_garden_pack', name: 'Coral Garden Pack', entry: 'dungeontypes/coral_garden.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'amber_marsh_pack', name: 'Amber Marsh Pack', entry: 'dungeontypes/amber_marsh.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'bamboo_hollows_pack', name: 'Bamboo Hollows Pack', entry: 'dungeontypes/bamboo_hollows.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'starlit_canopy_pack', name: 'Starlit Canopy Pack', entry: 'dungeontypes/starlit_canopy.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'prismatic_stalactites_pack', name: 'Prismatic Stalactites Pack', entry: 'dungeontypes/prismatic_stalactites.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'churning_karst_pack', name: 'Churning Karst Pack', entry: 'dungeontypes/churning_karst.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'echo_vaults_pack', name: 'Echo Vaults Pack', entry: 'dungeontypes/echo_vaults.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'emberglass_caverns_pack', name: 'Emberglass Caverns Pack', entry: 'dungeontypes/emberglass_caverns.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'abyssal_whorl_pack', name: 'Abyssal Whorl Pack', entry: 'dungeontypes/abyssal_whorl.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'ruined_labyrinth_pack', name: 'Ruined Labyrinth Pack', entry: 'dungeontypes/ruined_labyrinth.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'ancient_enigma_pack', name: 'Ancient Enigma Excavation Pack', entry: 'dungeontypes/ancient_enigma.js', version: '1.1.0', author: 'builtin-sample' },
  { id: 'sf_expansion_pack', name: 'SF Expansion Pack', entry: 'dungeontypes/sf_expansion.js', version: '1.0.0', author: 'builtin-sample' },
  { id: 'arabian_legends_pack', name: 'Arabian Legends Pack', entry: 'dungeontypes/arabian_legends_pack.js', version: '1.2.0', author: 'builtin-sample' },
  { id: 'multicolor_plains_pack', name: 'Multicolor Plains Pack', entry: 'dungeontypes/plains_variations_pack.js', version: '1.0.0', author: 'builtin-sample' }
];
