// MiniExp manifest (JS) — file:// 対応版
// グローバルに配列を公開します。main.js 側がこれを読み込みます。
window.MINIEXP_MANIFEST = [
  { id: 'snake',       name: 'スネーク',        entry: 'games/snake.js',       version: '0.1.0', author: 'builtin', description: '餌を取ると+1EXP', category: 'アクション' },
  { id: 'othello',     name: 'オセロ',          entry: 'games/othello.js',     version: '0.1.0', author: 'builtin', description: 'ひっくり返し×0.5EXP＋勝利ボーナス', category: 'ボード' },
  { id: 'checkers',    name: 'チェッカー',      entry: 'games/checkers.js',    version: '0.1.0', author: 'mod', description:
'ジャンプで駒取りしつつ王冠を目指すクラシックボードゲーム', category: 'ボード' },
  { id: 'chess',       name: 'チェス',          entry: 'games/chess.js',       version: '0.1.0', author: 'mod', description:
'駒の組み合わせで王を詰ませる本格チェス。駒取りとチェックでEXPを獲得', category: 'ボード' },
  { id: 'xiangqi',     name: 'シャンチー',      entry: 'games/xiangqi.js',    version: '0.1.0', author: 'mod', description: '中国の将棋・象棋。駒取り・王手・詰みでEXPを稼ごう', category: 'ボード' },
  { id: 'shogi',       name: '将棋',            entry: 'games/shogi.js',       version: '0.1.0', author: 'mod', description:
'持ち駒と成りを駆使する本格将棋。指し手/捕獲/王手でEXP', category: 'ボード' },
  { id: 'connect6',    name: 'コネクトシックス', entry: 'games/stone_board_games.js', version: '0.1.0', author: 'mod', description: '六目並べ。配置+1/リーチ+10/勝利で高EXP', category: 'ボード' },
  { id: 'gomoku',      name: '五目並べ',        entry: 'games/stone_board_games.js', version: '0.1.0', author: 'mod', description: '配置+1/リーチ+10/勝利ボーナス', category: 'ボード' },
  { id: 'go',          name: '囲碁',            entry: 'games/go.js',             version: '0.1.0', author: 'mod', description: '配置+1/捕獲ボーナス/勝利EXP', category: 'ボード' },
  { id: 'connect4',    name: '四目並べ',        entry: 'games/stone_board_games.js', version: '0.1.0', author: 'mod', description: '落下式四目。配置+1/リーチ+10', category: 'ボード' },
  { id: 'tic_tac_toe', name: '三目並べ',        entry: 'games/stone_board_games.js', version: '0.1.0', author: 'mod', description: '配置+1/リーチ+10/シンプル勝利EXP', category: 'ボード' },
  { id: 'breakout',    name: 'ブロック崩し',    entry: 'games/breakout.js',    version: '0.1.0', author: 'builtin', description: 'ブロック破壊で+1EXP', category: 'アクション' },
  { id: 'breakout_k',  name: 'ブロック崩しk',  entry: 'games/breakout_keyboard.js', version: '0.1.0', author: 'builtin', description: 'バー操作はキーボード限定', category: 'アクション' },
  { id: 'pinball_xp',  name: 'XPピンボール',    entry: 'games/pinball.js',     version: '0.1.0', author: 'mod', description: '3Dピンボール風テーブル。バンパーやレーンでEXPを稼ごう', category: 'アクション' },
  { id: 'pong',        name: 'ピンポン',        entry: 'games/pong.js',        version: '0.1.0', author: 'builtin', description: 'マッチ勝利で EASY+1 / NORMAL+5 / HARD+25', category: 'アクション' },
  { id: 'same',        name: 'セイムゲーム',    entry: 'games/same.js',        version: '0.1.0', author: 'builtin', description: '同色まとめ消し×0.5EXP', category: 'パズル' },
  { id: 'match3',      name: 'マッチ3',          entry: 'games/match3.js',      version: '0.1.0', author: 'builtin', description: '3:+1 / 4:+3 / 5:+10、連鎖×1.5', category: 'パズル' },
  { id: 'minesweeper', name: 'マインスイーパー', entry: 'games/minesweeper.js', version: '0.1.0', author: 'builtin', description: '開放×0.1 / クリア: 25/200/1600', category: 'パズル' },
  { id: 'sudoku',      name: 'ナンプレ',        entry: 'games/sudoku.js',     version: '0.1.0', author: 'mod', description: '正解入力でEXP / クリアボーナス', category: 'パズル' },
  { id: 'ultimate_ttt', name: 'スーパー三目並べ', entry: 'games/ultimate_ttt.js', version: '0.1.0', author: 'mod', description: '小盤制覇+25/配置+1/リーチ+10/勝利ボーナス', category: 'ボード' },
  { id: 'sliding_puzzle', name: 'スライドパズル', entry: 'games/sliding_puzzle.js', version: '0.1.0', author: 'mod', description: '難易度で8/15/24のスライドパズル', category: 'パズル' },
  { id: 'invaders',    name: 'インベーダー風',    entry: 'games/invaders.js',   version: '0.1.0', author: 'builtin', description: '撃破+1 / 全滅+50', category: 'シューティング' },
  { id: 'pacman',      name: 'パックマン風',      entry: 'games/pacman.js',     version: '0.1.0', author: 'builtin', description: '餌+0.5 / 全取得+100', category: 'アクション' },
  { id: 'tetris',      name: 'テトリス風',        entry: 'games/tetris.js',     version: '0.1.0', author: 'builtin', description: 'REN×1.5^n / T-Spin', category: 'パズル' },
  { id: 'falling_puyos', name: 'ぷよぷよ風',      entry: 'games/puyo.js',      version: '0.1.0', author: 'mod', description: '4つ同色で消去。連鎖で倍率UP', category: 'パズル' },
  { id: 'triomino_columns', name: 'トリオミノコラムス', entry: 'games/triomino_columns.js', version: '0.1.0', author: 'mod', description: 'トリオトスDX風！ラインスパーク＆ホールド対応', category: 'パズル' },
  { id: 'game2048',    name: '2048',             entry: 'games/2048.js',       version: '0.1.0', author: 'builtin', description: '合成log2 / 2048で+777', category: 'パズル' },
  // New mini-games (MOD)
  { id: 'todo_list',   name: 'ToDoリスト',       entry: 'games/todo_list.js',  version: '0.1.0', author: 'mod', description: 'タスク完了で設定EXP / 失敗は獲得なし', category: 'ユーティリティ' },
  { id: 'counter_pad', name: 'カウンターパッド', entry: 'games/counter.js',     version: '0.1.0', author: 'mod', description: '数値を増減するだけのマルチカウンター。操作内容は自動保存', category: 'ユーティリティ' },
  { id: 'notepad',     name: 'メモ帳',           entry: 'games/notepad.js',    version: '0.1.0', author: 'mod', description: '開く+5 / 編集+1 / 保存+5 EXP', category: 'ユーティリティ' },
  { id: 'exceler',    name: '表計算エクセラー', entry: 'games/exceler.js', version: '0.1.0', author: 'mod', description: 'XLSXの読み書きと主要関数・書式対応の軽量スプレッドシート', category: 'ユーティリティ' },
  { id: 'paint',       name: 'ペイント',         entry: 'games/paint.js',      version: '0.1.0', author: 'mod', description: '描画+1 / 塗りつぶし+3 / 保存+8 EXP', category: 'ユーティリティ' },
  { id: 'diagram_maker', name: 'ダイアグラムメーカー', entry: 'games/diagram_maker.js', version: '0.1.0', author: 'mod', description: 'draw.io XMLとPNG/JPG/BMP出力に対応した図表作成ユーティリティ', category: 'ユーティリティ' },
  { id: 'clock_hub',   name: '時計ハブ',         entry: 'games/clock_hub.js',  version: '0.1.0', author: 'mod', description: '多彩な時計と時間情報、節目EXPを備えたユーティリティ', category: 'ユーティリティ' },
  { id: 'stopwatch',   name: 'ストップウォッチ', entry: 'games/stopwatch.js',  version: '0.1.0', author: 'mod', description: 'ラップ計測に対応したストップウォッチ。操作でEXPを獲得', category: 'ユーティリティ' },
  { id: 'calculator',  name: '電卓',             entry: 'games/calculator.js', version: '0.1.0', author: 'mod', description: 'ユーティリティ電卓。数字入力+1 / 計算確定+5EXP', category: 'ユーティリティ' },
  { id: 'timer',       name: 'タイマー',         entry: 'games/timer.js',      version: '0.1.0', author: 'mod', description: 'カウントダウンとストップウォッチで時間管理', category: 'ユーティリティ' },
  { id: 'math_lab',    name: '数学ラボ',         entry: 'games/math_lab.js',   version: '0.1.0', author: 'mod', description: '高度な関数・単位変換・グラフ・テトレーション対応の数学ワークステーション', category: 'ユーティリティ' },
  { id: 'calc_combo',  name: '計算コンボ',       entry: 'games/calc_combo.js', version: '0.1.0', author: 'mod', description: '2桁までの四則演算をテンポ良く解いてコンボEXPを稼ぐ高速暗算ゲーム', category: 'パズル' },
  { id: 'blockcode',   name: 'ブロックコードラボ', entry: 'games/blockcode.js', version: '0.1.0', author: 'mod', description: 'Scratch風のブロックでミニゲームAPIを安全に試せるビジュアルプログラミング環境', category: 'ユーティリティ' },
  { id: 'wording',     name: 'Wording',         entry: 'games/wording.js',    version: '0.1.0', author: 'mod', description: '編集+1 / 書式+2 / 保存+6 EXP のワープロ', category: 'ユーティリティ' },
  { id: 'video_player', name: '動画プレイヤー', entry: 'games/video_player.js', version: '0.1.0', author: 'mod', description: 'ローカル動画とYouTubeの視聴でEXPを獲得できるユーティリティ', category: 'ユーティリティ' },
  { id: 'pomodoro',    name: 'ポモドーロタイマー', entry: 'games/pomodoro.js',  version: '0.1.0', author: 'mod', description: '集中と休憩のサイクル管理で完了ごとにEXPを得られるタイマー', category: 'ユーティリティ' },
  { id: 'music_player', name: 'ミュージックプレイヤー', entry: 'games/music_player.js', version: '0.1.0', author: 'mod', description: 'ローカル音源再生・視覚化・EQ搭載。再生や取り込みでEXP獲得', category: 'ユーティリティ' },
  { id: 'tester',      name: 'JSテスター',       entry: 'games/tester.js',     version: '0.1.0', author: 'mod', description: 'JS機能テストとCPUベンチマーク、ブロック式アドベンチャー作成ツール', category: 'ユーティリティ' },
  { id: 'system',      name: 'システム',         entry: 'games/system.js',     version: '0.1.0', author: 'mod', description: 'PC/OS/ブラウザ/IPを横断的に確認できるシステム情報ユーティリティ', category: 'ユーティリティ' },
  { id: 'aim',           name: '的あて（エイム）',     entry: 'games/aim.js',             version: '0.1.0', author: 'builtin', description: '命中で1〜3EXP／連続命中ボーナス', category: 'シューティング' },
  { id: 'dodge_race',    name: '回避レース',           entry: 'games/dodge_race.js',       version: '0.1.0', author: 'builtin', description: '距離で微量EXP／CP+5', category: 'アクション' },
  { id: 'pseudo3d_race', name: 'ハイウェイチェイサー', entry: 'games/pseudo3d_race.js',    version: '0.1.0', author: 'mod', description: '疑似3D高速道路で交通を追い抜け。距離+0.5/追い越し+4/セクション+25', category: 'アクション' },
  { id: 'topdown_race',  name: 'Aurora Circuit',       entry: 'games/topdown_race.js',     version: '0.1.0', author: 'mod', description: '見下ろし型周回レース。ラップと順位でEXP獲得', category: 'アクション' },
  { id: 'falling_shooter', name: '落下ブロック・シューター', entry: 'games/falling_shooter.js', version: '0.1.0', author: 'builtin', description: '破壊で1〜数EXP（大きいほど高EXP）', category: 'シューティング' },
  { id: 'bubble_shooter', name: 'バブルシューター', entry: 'games/bubble_shooter.js', version: '0.1.0', author: 'mod', description: 'バブルを撃って3つ揃えで消去。浮いたバブルはまとめて落下', category: 'パズル' },
  { id: 'virus_buster',  name: 'ドクターマリオ風', entry: 'games/virus_buster.js', version: '0.1.0', author: 'mod', description: 'カプセルで4つ揃え！ウイルス退治でEXP獲得', category: 'パズル' },
  { id: 'sichuan', name: '四川省パズル', entry: 'games/sichuan.js', version: '0.1.0', author: 'mod', description: '麻雀牌のペアを線で繋いで消す四川省。連続消去でボーナスEXP', category: 'パズル' },
  { id: 'piano_tiles', name: 'リズムタイル', entry: 'games/piano_tiles.js', version: '0.1.0', author: 'mod', description: 'ピアノタイル風の4レーン譜面。タップとホールドをタイミング良く決めてコンボを伸ばそう', category: 'リズム' },
  { id: 'river_crossing', name: '川渡り',               entry: 'games/river_crossing.js',   version: '0.1.0', author: 'builtin', description: '1段前進+1／到達+50', category: 'アクション' },
  { id: 'whack_a_mole',  name: 'モグラたたき',         entry: 'games/whack_a_mole.js',     version: '0.1.0', author: 'builtin', description: '命中でEXP／連続命中ボーナス', category: 'アクション' },
  { id: 'xp_crane',      name: 'XPクレーンキャッチャー', entry: 'games/xp_crane.js',        version: '0.1.0', author: 'mod', description: 'クレーンを操作して経験値カプセルを掬い上げるミニゲーム。連続成功と特殊カプセルでEXPを稼ごう', category: 'アクション' },
  { id: 'steady_wire',   name: 'イライラ棒',           entry: 'games/steady_wire.js',      version: '0.1.0', author: 'mod', description: '毎回生成されるコースを外れず進むワイヤーループ。操作方法を選んで挑戦', category: 'アクション' },
  { id: 'flappy_bird',   name: 'フラッピーバード風',   entry: 'games/flappy_bird.js',      version: '0.1.0', author: 'mod', description: 'パイプ通過でEXP。連続成功でボーナス', category: 'アクション' },
  { id: 'dino_runner',   name: 'ダイノランナー',       entry: 'games/dino_runner.js',      version: '0.1.0', author: 'mod', description: '恐竜で障害物ジャンプ／距離EXP', category: 'アクション' },
  { id: 'forced_scroll_jump', name: '強制スクロールジャンプ', entry: 'games/forced_scroll_jump.js', version: '0.1.0', author: 'mod', description: '強制横スクロールで穴や鉄球を避けつつCXマークを集めてランクを目指す', category: 'アクション' },
  { id: 'ten_ten',       name: '1010パズル',           entry: 'games/ten_ten.js',          version: '0.1.0', author: 'builtin', description: 'ラインでEXP／クロス消しは倍増', category: 'パズル' },
  { id: 'trump_games',   name: 'トランプセレクション', entry: 'games/trump_games.js',      version: '0.1.0', author: 'mod', description: 'トランプゲームハブ（神経衰弱・ブラックジャック・ババ抜き収録）', category: 'ボード' },
  { id: 'gamble_hall',  name: 'ギャンブルホール',     entry: 'games/gamble_hall.js',  version: '0.1.0', author: 'mod', description: 'EXPを賭けるルーレットとパチンコスロットの複合MOD', category: 'ギャンブル' },
  { id: 'electro_instrument', name: '電子楽器スタジオ', entry: 'games/electro_instrument.js', version: '0.1.0', author: 'mod', description: 'ピアノ鍵盤と多彩な音色で自由に演奏し音ごとにEXP獲得', category: 'トイ' },
  { id: 'graphics_tester', name: '3Dグラフィックテスター', entry: 'games/graphics_tester.js', version: '0.1.0', author: 'mod', description: '3D技術デモとレイトレーシング風レンダリング・ベンチマーク搭載のトイ系テスター', category: 'トイ' },
  { id: 'physics_sandbox', name: '物理遊び', entry: 'games/physics_sandbox.js', version: '0.1.0', author: 'mod', description: '火・水・ツタ・雷・回路を組み合わせるトイ系物理サンドボックス', category: 'トイ' },
  { id: 'logic_circuit', name: '論理回路シミュレータ', entry: 'games/logic_circuit.js', version: '0.1.0', author: 'mod', description: '入力ソース・ゲート・出力を配置して論理回路をシミュレーション', category: 'トイ' },
  { id: 'circuit_simulator', name: '電気回路シミュレータ', entry: 'games/circuit_simulator.js', version: '0.1.0', author: 'mod', description: 'DC/AC電源・受動素子・計器で回路を構成し計測するトイ向け回路ラボ', category: 'トイ' },
  { id: 'memo_studio', name: '暗記スタジオ', entry: 'games/memory_app.js', version: '0.1.0', author: 'mod', description: 'フラッシュカードを登録し間隔反復で学習する暗記アプリ', category: 'トイ' },
  { id: 'typing',      name: 'タイピングチャレンジ', entry: 'games/typing.js',      version: '0.1.0', author: 'mod', description: '60秒タイプで正確さとスピードを競うタイピングチャレンジ', category: 'スキル' },
];
