// MiniExp manifest (JS) — file:// 対応版
// グローバルに配列を公開します。main.js 側がこれを読み込みます。
window.MINIEXP_MANIFEST = [
  {
    id: 'snake',
    name: 'スネーク',
    nameKey: 'selection.miniexp.games.snake.name',
    entry: 'games/snake.js',
    version: '0.1.0',
    author: 'builtin',
    description: '餌を取ると+1EXP',
    descriptionKey: 'selection.miniexp.games.snake.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'othello',
    name: 'オセロ',
    nameKey: 'selection.miniexp.games.othello.name',
    entry: 'games/othello.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'ひっくり返し×0.5EXP＋勝利ボーナス',
    descriptionKey: 'selection.miniexp.games.othello.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'exothello',
    name: '拡張オセロ',
    nameKey: 'selection.miniexp.games.exothello.name',
    entry: 'games/exothello.js',
    version: '0.1.0',
    author: 'mod',
    description: '可変サイズ・壁・特殊勝利条件を選べる拡張オセロ',
    descriptionKey: 'selection.miniexp.games.exothello.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'othello_weak',
    name: '最弱オセロ',
    nameKey: 'selection.miniexp.games.othello_weak.name',
    entry: 'games/othello_weak.js',
    version: '0.1.0',
    author: 'mod',
    description: '少ない石で勝利する最弱オセロ。難易度が高いほどAIが自滅',
    descriptionKey: 'selection.miniexp.games.othello_weak.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'checkers',
    name: 'チェッカー',
    nameKey: 'selection.miniexp.games.checkers.name',
    entry: 'games/checkers.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ジャンプで駒取りしつつ王冠を目指すクラシックボードゲーム',
    descriptionKey: 'selection.miniexp.games.checkers.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'chess',
    name: 'チェス',
    nameKey: 'selection.miniexp.games.chess.name',
    entry: 'games/chess.js',
    version: '0.1.0',
    author: 'mod',
    description: '駒の組み合わせで王を詰ませる本格チェス。駒取りとチェックでEXPを獲得',
    descriptionKey: 'selection.miniexp.games.chess.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'xiangqi',
    name: 'シャンチー',
    nameKey: 'selection.miniexp.games.xiangqi.name',
    entry: 'games/xiangqi.js',
    version: '0.1.0',
    author: 'mod',
    description: '中国の将棋・象棋。駒取り・王手・詰みでEXPを稼ごう',
    descriptionKey: 'selection.miniexp.games.xiangqi.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'shogi',
    name: '将棋',
    nameKey: 'selection.miniexp.games.shogi.name',
    entry: 'games/shogi.js',
    version: '0.1.0',
    author: 'mod',
    description: '持ち駒と成りを駆使する本格将棋。指し手/捕獲/王手でEXP',
    descriptionKey: 'selection.miniexp.games.shogi.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'riichi_mahjong',
    name: 'リーチ麻雀ライト',
    nameKey: 'selection.miniexp.games.riichi_mahjong.name',
    entry: 'games/mahjong.js',
    version: '0.1.0',
    author: 'mod',
    description: 'AI3人と東風1局を戦う簡易リーチ麻雀。リーチ/ツモ/ロンと点棒精算に対応',
    descriptionKey: 'selection.miniexp.games.riichi_mahjong.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'connect6',
    name: 'コネクトシックス',
    nameKey: 'selection.miniexp.games.connect6.name',
    entry: 'games/stone_board_games.js',
    version: '0.1.0',
    author: 'mod',
    description: '六目並べ。配置+1/リーチ+10/勝利で高EXP',
    descriptionKey: 'selection.miniexp.games.connect6.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'gomoku',
    name: '五目並べ',
    nameKey: 'selection.miniexp.games.gomoku.name',
    entry: 'games/stone_board_games.js',
    version: '0.1.0',
    author: 'mod',
    description: '配置+1/リーチ+10/勝利ボーナス',
    descriptionKey: 'selection.miniexp.games.gomoku.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'renju',
    name: '連珠',
    nameKey: 'selection.miniexp.games.renju.name',
    entry: 'games/stone_board_games.js',
    version: '0.1.0',
    author: 'mod',
    description: '禁手ルール付き五目並べ。配置+1/リーチ+10/勝利ボーナス',
    descriptionKey: 'selection.miniexp.games.renju.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'go',
    name: '囲碁',
    nameKey: 'selection.miniexp.games.go.name',
    entry: 'games/go.js',
    version: '0.1.0',
    author: 'mod',
    description: '配置+1/捕獲ボーナス/勝利EXP',
    descriptionKey: 'selection.miniexp.games.go.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'backgammon',
    name: 'バックギャモン',
    nameKey: 'selection.miniexp.games.backgammon.name',
    entry: 'games/backgammon.js',
    version: '0.1.0',
    author: 'mod',
    description: '24ポイントを駆け巡りベアリングオフを目指すバックギャモン。ヒットやベアオフでEXP獲得',
    descriptionKey: 'selection.miniexp.games.backgammon.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'connect4',
    name: '四目並べ',
    nameKey: 'selection.miniexp.games.connect4.name',
    entry: 'games/stone_board_games.js',
    version: '0.1.0',
    author: 'mod',
    description: '落下式四目。配置+1/リーチ+10',
    descriptionKey: 'selection.miniexp.games.connect4.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'tic_tac_toe',
    name: '三目並べ',
    nameKey: 'selection.miniexp.games.tic_tac_toe.name',
    entry: 'games/stone_board_games.js',
    version: '0.1.0',
    author: 'mod',
    description: '配置+1/リーチ+10/シンプル勝利EXP',
    descriptionKey: 'selection.miniexp.games.tic_tac_toe.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'mancala',
    name: 'マンカラ',
    nameKey: 'selection.miniexp.games.mancala.name',
    entry: 'games/mancala.js',
    version: '0.1.0',
    author: 'mod',
    description: 'カラハ式マンカラ。種まきと捕獲を駆使してAIと勝負',
    descriptionKey: 'selection.miniexp.games.mancala.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'breakout',
    name: 'ブロック崩し',
    nameKey: 'selection.miniexp.games.breakout.name',
    entry: 'games/breakout.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'ブロック破壊で+1EXP',
    descriptionKey: 'selection.miniexp.games.breakout.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'breakout_k',
    name: 'ブロック崩しk',
    nameKey: 'selection.miniexp.games.breakout_k.name',
    entry: 'games/breakout_keyboard.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'バー操作はキーボード限定',
    descriptionKey: 'selection.miniexp.games.breakout_k.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'sandbox_breakout',
    name: 'サンドボックスブロック崩し',
    nameKey: 'minigame.games.sandbox_breakout.name',
    entry: 'games/sandbox_breakout.js',
    version: '0.1.0',
    author: 'mod',
    description: '作ったステージをすぐにプレイできるブロック崩し。カスタム硬さとインポート/エクスポート対応',
    descriptionKey: 'minigame.games.sandbox_breakout.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'pinball_xp',
    name: 'XPピンボール',
    nameKey: 'selection.miniexp.games.pinball_xp.name',
    entry: 'games/pinball.js',
    version: '0.1.0',
    author: 'mod',
    description: '3Dピンボール風テーブル。バンパーやレーンでEXPを稼ごう',
    descriptionKey: 'selection.miniexp.games.pinball_xp.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'dungeon_td',
    name: 'ダンジョンタワーディフェンス',
    nameKey: 'selection.miniexp.games.dungeon_td.name',
    entry: 'games/dungeon_tower_defense.js',
    version: '0.1.0',
    author: 'mod',
    description: '混合型ダンジョンで砲塔を設置し迫る敵波を迎撃するタワーディフェンス',
    descriptionKey: 'selection.miniexp.games.dungeon_td.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'pong',
    name: 'ピンポン',
    nameKey: 'selection.miniexp.games.pong.name',
    entry: 'games/pong.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'マッチ勝利で EASY+1 / NORMAL+5 / HARD+25',
    descriptionKey: 'selection.miniexp.games.pong.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'same',
    name: 'セイムゲーム',
    nameKey: 'selection.miniexp.games.same.name',
    entry: 'games/same.js',
    version: '0.1.0',
    author: 'builtin',
    description: '同色まとめ消し×0.5EXP',
    descriptionKey: 'selection.miniexp.games.same.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'match3',
    name: 'マッチ3',
    nameKey: 'selection.miniexp.games.match3.name',
    entry: 'games/match3.js',
    version: '0.1.0',
    author: 'builtin',
    description: '3:+1 / 4:+3 / 5:+10、連鎖×1.5',
    descriptionKey: 'selection.miniexp.games.match3.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'minesweeper',
    name: 'マインスイーパー',
    nameKey: 'selection.miniexp.games.minesweeper.name',
    entry: 'games/minesweeper.js',
    version: '0.1.0',
    author: 'builtin',
    description: '開放×0.1 / クリア: 25/200/1600',
    descriptionKey: 'selection.miniexp.games.minesweeper.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'sudoku',
    name: 'ナンプレ',
    nameKey: 'selection.miniexp.games.sudoku.name',
    entry: 'games/sudoku.js',
    version: '0.1.0',
    author: 'mod',
    description: '正解入力でEXP / クリアボーナス',
    descriptionKey: 'selection.miniexp.games.sudoku.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'ultimate_ttt',
    name: 'スーパー三目並べ',
    nameKey: 'selection.miniexp.games.ultimate_ttt.name',
    entry: 'games/ultimate_ttt.js',
    version: '0.1.0',
    author: 'mod',
    description: '小盤制覇+25/配置+1/リーチ+10/勝利ボーナス',
    descriptionKey: 'selection.miniexp.games.ultimate_ttt.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'nine_mens_morris',
    name: 'ナイン・メンズ・モリス',
    nameKey: 'selection.miniexp.games.nine_mens_morris.name',
    entry: 'games/nine_mens_morris.js',
    version: '0.1.0',
    author: 'mod',
    description: '配置+1 / ミル+15 / 勝利ボーナス',
    descriptionKey: 'selection.miniexp.games.nine_mens_morris.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'sugoroku_life',
    name: '人生すごろく',
    nameKey: 'selection.miniexp.games.sugoroku_life.name',
    entry: 'games/sugoroku_life.js',
    version: '0.1.0',
    author: 'mod',
    description: 'キャリアイベントを乗り越えて資産とEXPを伸ばす人生風すごろく',
    descriptionKey: 'selection.miniexp.games.sugoroku_life.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'sliding_puzzle',
    name: 'スライドパズル',
    nameKey: 'selection.miniexp.games.sliding_puzzle.name',
    entry: 'games/sliding_puzzle.js',
    version: '0.1.0',
    author: 'mod',
    description: '難易度で8/15/24のスライドパズル',
    descriptionKey: 'selection.miniexp.games.sliding_puzzle.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'jigsaw_puzzle',
    name: 'ジグソーパズル',
    nameKey: 'selection.miniexp.games.jigsaw_puzzle.name',
    entry: 'games/jigsaw_puzzle.js',
    version: '0.1.0',
    author: 'mod',
    description: '任意の画像と行列数を設定できるジグソーパズル',
    descriptionKey: 'selection.miniexp.games.jigsaw_puzzle.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'sandbox_sokoban',
    name: 'サンドボックス倉庫番',
    nameKey: 'selection.miniexp.games.sandbox_sokoban.name',
    entry: 'games/sandbox_sokoban.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ステージ編集とプレイをシームレスに行き来できる倉庫番。木箱+25EXP/クリア+100EXP',
    descriptionKey: 'selection.miniexp.games.sandbox_sokoban.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'invaders',
    name: 'インベーダー風',
    nameKey: 'selection.miniexp.games.invaders.name',
    entry: 'games/invaders.js',
    version: '0.1.0',
    author: 'builtin',
    description: '撃破+1 / 全滅+50',
    descriptionKey: 'selection.miniexp.games.invaders.description',
    category: 'シューティング',
    categories: ['シューティング'],
    categoryIds: ['shooting']
  },
  {
    id: 'pacman',
    name: 'パックマン風',
    nameKey: 'selection.miniexp.games.pacman.name',
    entry: 'games/pacman.js',
    version: '0.1.0',
    author: 'builtin',
    description: '餌+0.5 / 全取得+100',
    descriptionKey: 'selection.miniexp.games.pacman.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'bomberman',
    name: 'ボンバーマン風',
    nameKey: 'selection.miniexp.games.bomberman.name',
    entry: 'games/bomberman.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ソフトブロック破壊+3 / 敵撃破+12 / 全滅+75',
    descriptionKey: 'selection.miniexp.games.bomberman.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'tetris',
    name: 'テトリス風',
    nameKey: 'selection.miniexp.games.tetris.name',
    entry: 'games/tetris.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'REN×1.5^n / T-Spin',
    descriptionKey: 'selection.miniexp.games.tetris.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'falling_puyos',
    name: 'ぷよぷよ風',
    nameKey: 'selection.miniexp.games.falling_puyos.name',
    entry: 'games/puyo.js',
    version: '0.1.0',
    author: 'mod',
    description: '4つ同色で消去。連鎖で倍率UP',
    descriptionKey: 'selection.miniexp.games.falling_puyos.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'triomino_columns',
    name: 'トリオミノコラムス',
    nameKey: 'selection.miniexp.games.triomino_columns.name',
    entry: 'games/triomino_columns.js',
    version: '0.1.0',
    author: 'mod',
    description: 'トリオトスDX風！ラインスパーク＆ホールド対応',
    descriptionKey: 'selection.miniexp.games.triomino_columns.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'game2048',
    name: '2048',
    nameKey: 'selection.miniexp.games.game2048.name',
    entry: 'games/2048.js',
    version: '0.1.0',
    author: 'builtin',
    description: '合成log2 / 2048で+777',
    descriptionKey: 'selection.miniexp.games.game2048.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'todo_list',
    name: 'ToDoリスト',
    nameKey: 'selection.miniexp.games.todo_list.name',
    entry: 'games/todo_list.js',
    version: '0.1.0',
    author: 'mod',
    description: 'タスク完了で設定EXP / 失敗は獲得なし',
    descriptionKey: 'selection.miniexp.games.todo_list.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'counter_pad',
    name: 'カウンターパッド',
    nameKey: 'selection.miniexp.games.counter_pad.name',
    entry: 'games/counter.js',
    version: '0.1.0',
    author: 'mod',
    description: '数値を増減するだけのマルチカウンター。操作内容は自動保存',
    descriptionKey: 'selection.miniexp.games.counter_pad.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'random_tool',
    name: 'ランダムツール',
    nameKey: 'selection.miniexp.games.random_tool.name',
    entry: 'games/random_tool.js',
    version: '0.1.0',
    author: 'mod',
    description: 'サイコロ・ルーレット・ランダム選択・乱数/文字列生成を備えたユーティリティ',
    descriptionKey: 'selection.miniexp.games.random_tool.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'notepad',
    name: 'メモ帳',
    nameKey: 'selection.miniexp.games.notepad.name',
    entry: 'games/notepad.js',
    version: '0.1.0',
    author: 'mod',
    description: '開く+5 / 編集+1 / 保存+5 EXP',
    descriptionKey: 'selection.miniexp.games.notepad.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'exceler',
    name: '表計算エクセラー',
    nameKey: 'selection.miniexp.games.exceler.name',
    entry: 'games/exceler.js',
    version: '0.1.0',
    author: 'mod',
    description: 'XLSXの読み書きと主要関数・書式対応の軽量スプレッドシート',
    descriptionKey: 'selection.miniexp.games.exceler.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'paint',
    name: 'ペイント',
    nameKey: 'selection.miniexp.games.paint.name',
    entry: 'games/paint.js',
    version: '0.1.0',
    author: 'mod',
    description: '描画+1 / 塗りつぶし+3 / 保存+8 EXP',
    descriptionKey: 'selection.miniexp.games.paint.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'diagram_maker',
    name: 'ダイアグラムメーカー',
    nameKey: 'selection.miniexp.games.diagram_maker.name',
    entry: 'games/diagram_maker.js',
    version: '0.1.0',
    author: 'mod',
    description: 'draw.io XMLとPNG/JPG/BMP出力に対応した図表作成ユーティリティ',
    descriptionKey: 'selection.miniexp.games.diagram_maker.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'clock_hub',
    name: '時計ハブ',
    nameKey: 'selection.miniexp.games.clock_hub.name',
    entry: 'games/clock_hub.js',
    version: '0.1.0',
    author: 'mod',
    description: '多彩な時計と時間情報、節目EXPを備えたユーティリティ',
    descriptionKey: 'selection.miniexp.games.clock_hub.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'login_bonus',
    name: 'ログインボーナス',
    nameKey: 'selection.miniexp.games.login_bonus.name',
    entry: 'games/login_bonus.js',
    version: '0.1.0',
    author: 'mod',
    description: 'カレンダーで毎日のログインボーナスを受け取り記録できます',
    descriptionKey: 'selection.miniexp.games.login_bonus.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'stopwatch',
    name: 'ストップウォッチ',
    nameKey: 'selection.miniexp.games.stopwatch.name',
    entry: 'games/stopwatch.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ラップ計測に対応したストップウォッチ。操作でEXPを獲得',
    descriptionKey: 'selection.miniexp.games.stopwatch.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'calculator',
    name: '電卓',
    nameKey: 'selection.miniexp.games.calculator.name',
    entry: 'games/calculator.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ユーティリティ電卓。数字入力+1 / 計算確定+5EXP',
    descriptionKey: 'selection.miniexp.games.calculator.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'timer',
    name: 'タイマー',
    nameKey: 'selection.miniexp.games.timer.name',
    entry: 'games/timer.js',
    version: '0.1.0',
    author: 'mod',
    description: 'カウントダウンとストップウォッチで時間管理',
    descriptionKey: 'selection.miniexp.games.timer.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'math_lab',
    name: '数学ラボ',
    nameKey: 'selection.miniexp.games.math_lab.name',
    entry: 'games/math_lab.js',
    version: '0.1.0',
    author: 'mod',
    description: '高度な関数・単位変換・グラフ・テトレーション対応の数学ワークステーション',
    descriptionKey: 'selection.miniexp.games.math_lab.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'calc_combo',
    name: '計算コンボ',
    nameKey: 'selection.miniexp.games.calc_combo.name',
    entry: 'games/calc_combo.js',
    version: '0.1.0',
    author: 'mod',
    description: '2桁までの四則演算をテンポ良く解いてコンボEXPを稼ぐ高速暗算ゲーム',
    descriptionKey: 'selection.miniexp.games.calc_combo.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'blockcode',
    name: 'ブロックコードラボ',
    nameKey: 'selection.miniexp.games.blockcode.name',
    entry: 'games/blockcode.js',
    version: '0.1.0',
    author: 'mod',
    description: 'Scratch風のブロックでミニゲームAPIを安全に試せるビジュアルプログラミング環境',
    descriptionKey: 'selection.miniexp.games.blockcode.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'wording',
    name: 'Wording',
    nameKey: 'selection.miniexp.games.wording.name',
    entry: 'games/wording.js',
    version: '0.1.0',
    author: 'mod',
    description: '編集+1 / 書式+2 / 保存+6 EXP のワープロ',
    descriptionKey: 'selection.miniexp.games.wording.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'video_player',
    name: '動画プレイヤー',
    nameKey: 'selection.miniexp.games.video_player.name',
    entry: 'games/video_player.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ローカル動画とYouTubeの視聴でEXPを獲得できるユーティリティ',
    descriptionKey: 'selection.miniexp.games.video_player.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'image_viewer_mod',
    name: '画像ビューアMOD',
    nameKey: 'selection.miniexp.games.image_viewer_mod.name',
    entry: 'games/image_viewer_mod.js',
    version: '0.1.0',
    author: 'mod',
    description: '画像を開いてEXP獲得、パン操作で距離に応じて経験値が入るユーティリティ',
    descriptionKey: 'selection.miniexp.games.image_viewer_mod.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'pomodoro',
    name: 'ポモドーロタイマー',
    nameKey: 'selection.miniexp.games.pomodoro.name',
    entry: 'games/pomodoro.js',
    version: '0.1.0',
    author: 'mod',
    description: '集中と休憩のサイクル管理で完了ごとにEXPを得られるタイマー',
    descriptionKey: 'selection.miniexp.games.pomodoro.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'music_player',
    name: 'ミュージックプレイヤー',
    nameKey: 'selection.miniexp.games.music_player.name',
    entry: 'games/music_player.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ローカル音源再生・視覚化・EQ搭載。再生や取り込みでEXP獲得',
    descriptionKey: 'selection.miniexp.games.music_player.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'tester',
    name: 'JSテスター',
    nameKey: 'selection.miniexp.games.tester.name',
    entry: 'games/tester.js',
    version: '0.1.0',
    author: 'mod',
    description: 'JS機能テストとCPUベンチマーク、ブロック式アドベンチャー作成ツール',
    descriptionKey: 'selection.miniexp.games.tester.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'system',
    name: 'システム',
    nameKey: 'selection.miniexp.games.system.name',
    entry: 'games/system.js',
    version: '0.1.0',
    author: 'mod',
    description: 'PC/OS/ブラウザ/IPを横断的に確認できるシステム情報ユーティリティ',
    descriptionKey: 'selection.miniexp.games.system.description',
    category: 'ユーティリティ',
    categories: ['ユーティリティ'],
    categoryIds: ['utility']
  },
  {
    id: 'aim',
    name: '的あて（エイム）',
    nameKey: 'selection.miniexp.games.aim.name',
    entry: 'games/aim.js',
    version: '0.1.0',
    author: 'builtin',
    description: '命中で1〜3EXP／連続命中ボーナス',
    descriptionKey: 'selection.miniexp.games.aim.description',
    category: 'シューティング',
    categories: ['シューティング'],
    categoryIds: ['shooting']
  },
  {
    id: 'dodge_race',
    name: '回避レース',
    nameKey: 'selection.miniexp.games.dodge_race.name',
    entry: 'games/dodge_race.js',
    version: '0.1.0',
    author: 'builtin',
    description: '距離で微量EXP／CP+5',
    descriptionKey: 'selection.miniexp.games.dodge_race.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'pseudo3d_race',
    name: 'ハイウェイチェイサー',
    nameKey: 'selection.miniexp.games.pseudo3d_race.name',
    entry: 'games/pseudo3d_race.js',
    version: '0.1.0',
    author: 'mod',
    description: '疑似3D高速道路で交通を追い抜け。距離+0.5/追い越し+4/セクション+25',
    descriptionKey: 'selection.miniexp.games.pseudo3d_race.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'bowling_duel',
    name: 'ボウリング対決',
    nameKey: 'selection.miniexp.games.bowling_duel.name',
    entry: 'games/bowling.js',
    version: '0.1.0',
    author: 'mod',
    description: 'カーブ・狙い・パワーを調整してCPUと10フレーム勝負するボウリングMOD',
    descriptionKey: 'selection.miniexp.games.bowling_duel.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'topdown_race',
    name: 'Aurora Circuit',
    nameKey: 'selection.miniexp.games.topdown_race.name',
    entry: 'games/topdown_race.js',
    version: '0.1.0',
    author: 'mod',
    description: '見下ろし型周回レース。ラップと順位でEXP獲得',
    descriptionKey: 'selection.miniexp.games.topdown_race.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'falling_shooter',
    name: '落下ブロック・シューター',
    nameKey: 'selection.miniexp.games.falling_shooter.name',
    entry: 'games/falling_shooter.js',
    version: '0.1.0',
    author: 'builtin',
    description: '破壊で1〜数EXP（大きいほど高EXP）',
    descriptionKey: 'selection.miniexp.games.falling_shooter.description',
    category: 'シューティング',
    categories: ['シューティング'],
    categoryIds: ['shooting']
  },
  {
    id: 'bubble_shooter',
    name: 'バブルシューター',
    nameKey: 'selection.miniexp.games.bubble_shooter.name',
    entry: 'games/bubble_shooter.js',
    version: '0.1.0',
    author: 'mod',
    description: 'バブルを撃って3つ揃えで消去。浮いたバブルはまとめて落下',
    descriptionKey: 'selection.miniexp.games.bubble_shooter.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'virus_buster',
    name: 'ドクターマリオ風',
    nameKey: 'selection.miniexp.games.virus_buster.name',
    entry: 'games/virus_buster.js',
    version: '0.1.0',
    author: 'mod',
    description: 'カプセルで4つ揃え！ウイルス退治でEXP獲得',
    descriptionKey: 'selection.miniexp.games.virus_buster.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'sichuan',
    name: '四川省パズル',
    nameKey: 'selection.miniexp.games.sichuan.name',
    entry: 'games/sichuan.js',
    version: '0.1.0',
    author: 'mod',
    description: '麻雀牌のペアを線で繋いで消す四川省。連続消去でボーナスEXP',
    descriptionKey: 'selection.miniexp.games.sichuan.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'piano_tiles',
    name: 'リズムタイル',
    nameKey: 'selection.miniexp.games.piano_tiles.name',
    entry: 'games/piano_tiles.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ピアノタイル風の4レーン譜面。タップとホールドをタイミング良く決めてコンボを伸ばそう',
    descriptionKey: 'selection.miniexp.games.piano_tiles.description',
    category: 'リズム',
    categories: ['リズム'],
    categoryIds: ['rhythm']
  },
  {
    id: 'taiko_drum',
    name: '太鼓リズム',
    nameKey: 'selection.miniexp.games.taiko_drum.name',
    entry: 'games/taiko_drum.js',
    version: '0.1.0',
    author: 'mod',
    description: '太鼓の達人風の2面譜面。良/可/普/不の判定とコンボEXPボーナスを搭載',
    descriptionKey: 'selection.miniexp.games.taiko_drum.description',
    category: 'リズム',
    categories: ['リズム'],
    categoryIds: ['rhythm']
  },
  {
    id: 'river_crossing',
    name: '川渡り',
    nameKey: 'selection.miniexp.games.river_crossing.name',
    entry: 'games/river_crossing.js',
    version: '0.1.0',
    author: 'builtin',
    description: '1段前進+1／到達+50',
    descriptionKey: 'selection.miniexp.games.river_crossing.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'whack_a_mole',
    name: 'モグラたたき',
    nameKey: 'selection.miniexp.games.whack_a_mole.name',
    entry: 'games/whack_a_mole.js',
    version: '0.1.0',
    author: 'builtin',
    description: '命中でEXP／連続命中ボーナス',
    descriptionKey: 'selection.miniexp.games.whack_a_mole.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'xp_crane',
    name: 'XPクレーンキャッチャー',
    nameKey: 'selection.miniexp.games.xp_crane.name',
    entry: 'games/xp_crane.js',
    version: '0.1.0',
    author: 'mod',
    description: 'クレーンを操作して経験値カプセルを掬い上げるミニゲーム。連続成功と特殊カプセルでEXPを稼ごう',
    descriptionKey: 'selection.miniexp.games.xp_crane.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'steady_wire',
    name: 'イライラ棒',
    nameKey: 'selection.miniexp.games.steady_wire.name',
    entry: 'games/steady_wire.js',
    version: '0.1.0',
    author: 'mod',
    description: '毎回生成されるコースを外れず進むワイヤーループ。操作方法を選んで挑戦',
    descriptionKey: 'selection.miniexp.games.steady_wire.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'flappy_bird',
    name: 'フラッピーバード風',
    nameKey: 'selection.miniexp.games.flappy_bird.name',
    entry: 'games/flappy_bird.js',
    version: '0.1.0',
    author: 'mod',
    description: 'パイプ通過でEXP。連続成功でボーナス',
    descriptionKey: 'selection.miniexp.games.flappy_bird.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'dino_runner',
    name: 'ダイノランナー',
    nameKey: 'selection.miniexp.games.dino_runner.name',
    entry: 'games/dino_runner.js',
    version: '0.1.0',
    author: 'mod',
    description: '恐竜で障害物ジャンプ／距離EXP',
    descriptionKey: 'selection.miniexp.games.dino_runner.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'floor_descent',
    name: 'フロア降りサバイバル',
    nameKey: 'selection.miniexp.games.floor_descent.name',
    entry: 'games/floor_descent.js',
    version: '0.1.0',
    author: 'mod',
    description: '迫る針天井から逃げながら下へ進む縦スクロールアクション。足場ギミックで差をつけよう',
    descriptionKey: 'selection.miniexp.games.floor_descent.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'forced_scroll_jump',
    name: '強制スクロールジャンプ',
    nameKey: 'selection.miniexp.games.forced_scroll_jump.name',
    entry: 'games/forced_scroll_jump.js',
    version: '0.1.0',
    author: 'mod',
    description: '強制横スクロールで穴や鉄球を避けつつCXマークを集めてランクを目指す',
    descriptionKey: 'selection.miniexp.games.forced_scroll_jump.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'tosochu',
    name: '逃走中',
    nameKey: 'selection.miniexp.games.tosochu.name',
    entry: 'games/tosochu.js',
    version: '0.1.0',
    author: 'mod',
    description: '逃走者 VS ハンターの番組風アクション。逃げ切れば+10000EXP、自首で蓄積EXP',
    descriptionKey: 'selection.miniexp.games.tosochu.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'treasure_hunt',
    name: '宝探しダンジョン',
    nameKey: 'selection.miniexp.games.treasure_hunt.name',
    entry: 'games/treasure_hunt.js',
    version: '0.1.0',
    author: 'mod',
    description: '生成される混合型ダンジョンで宝を探し、距離と時間で指数EXPを稼ぐ探索アクション',
    descriptionKey: 'selection.miniexp.games.treasure_hunt.description',
    category: 'アクション',
    categories: ['アクション'],
    categoryIds: ['action']
  },
  {
    id: 'ten_ten',
    name: '1010パズル',
    nameKey: 'selection.miniexp.games.ten_ten.name',
    entry: 'games/ten_ten.js',
    version: '0.1.0',
    author: 'builtin',
    description: 'ラインでEXP／クロス消しは倍増',
    descriptionKey: 'selection.miniexp.games.ten_ten.description',
    category: 'パズル',
    categories: ['パズル'],
    categoryIds: ['puzzle']
  },
  {
    id: 'trump_games',
    name: 'トランプセレクション',
    nameKey: 'selection.miniexp.games.trump_games.name',
    entry: 'games/trump_games.js',
    version: '0.1.0',
    author: 'mod',
    description: 'トランプゲームハブ（神経衰弱・ブラックジャック・ババ抜き収録）',
    descriptionKey: 'selection.miniexp.games.trump_games.description',
    category: 'ボード',
    categories: ['ボード'],
    categoryIds: ['board']
  },
  {
    id: 'gamble_hall',
    name: 'ギャンブルホール',
    nameKey: 'selection.miniexp.games.gamble_hall.name',
    entry: 'games/gamble_hall.js',
    version: '0.1.0',
    author: 'mod',
    description: 'EXPを賭けるルーレットとパチンコスロットの複合MOD',
    descriptionKey: 'selection.miniexp.games.gamble_hall.description',
    category: 'ギャンブル',
    categories: ['ギャンブル'],
    categoryIds: ['gambling']
  },
  {
    id: 'electro_instrument',
    name: '電子楽器スタジオ',
    nameKey: 'selection.miniexp.games.electro_instrument.name',
    entry: 'games/electro_instrument.js',
    version: '0.1.0',
    author: 'mod',
    description: 'ピアノ鍵盤と多彩な音色で自由に演奏し音ごとにEXP獲得',
    descriptionKey: 'selection.miniexp.games.electro_instrument.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'graphics_tester',
    name: '3Dグラフィックテスター',
    nameKey: 'selection.miniexp.games.graphics_tester.name',
    entry: 'games/graphics_tester.js',
    version: '0.1.0',
    author: 'mod',
    description: '3D技術デモとレイトレーシング風レンダリング・ベンチマーク搭載のトイ系テスター',
    descriptionKey: 'selection.miniexp.games.graphics_tester.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'physics_sandbox',
    name: '物理遊び',
    nameKey: 'selection.miniexp.games.physics_sandbox.name',
    entry: 'games/physics_sandbox.js',
    version: '0.1.0',
    author: 'mod',
    description: '火・水・ツタ・雷・回路を組み合わせるトイ系物理サンドボックス',
    descriptionKey: 'selection.miniexp.games.physics_sandbox.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'populite',
    name: 'ポピュラス風',
    nameKey: 'selection.miniexp.games.populite.name',
    entry: 'games/populite.js',
    version: '0.1.0',
    author: 'mod',
    description: '地形整備と信仰力で人口目標を達成するリアルタイム神シミュレーション',
    descriptionKey: 'selection.miniexp.games.populite.description',
    category: 'シミュレーション',
    categories: ['シミュレーション'],
    categoryIds: ['simulation']
  },
  {
    id: 'logic_circuit',
    name: '論理回路シミュレータ',
    nameKey: 'selection.miniexp.games.logic_circuit.name',
    entry: 'games/logic_circuit.js',
    version: '0.1.0',
    author: 'mod',
    description: '入力ソース・ゲート・出力を配置して論理回路をシミュレーション',
    descriptionKey: 'selection.miniexp.games.logic_circuit.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'circuit_simulator',
    name: '電気回路シミュレータ',
    nameKey: 'selection.miniexp.games.circuit_simulator.name',
    entry: 'games/circuit_simulator.js',
    version: '0.1.0',
    author: 'mod',
    description: 'DC/AC電源・受動素子・計器で回路を構成し計測するトイ向け回路ラボ',
    descriptionKey: 'selection.miniexp.games.circuit_simulator.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'memo_studio',
    name: '暗記スタジオ',
    nameKey: 'selection.miniexp.games.memo_studio.name',
    entry: 'games/memory_app.js',
    version: '0.1.0',
    author: 'mod',
    description: 'フラッシュカードを登録し間隔反復で学習する暗記アプリ',
    descriptionKey: 'selection.miniexp.games.memo_studio.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'onigokko',
    name: '鬼ごっこ',
    nameKey: 'selection.miniexp.games.onigokko.name',
    entry: 'games/onigokko.js',
    version: '0.1.0',
    author: 'mod',
    description: '混合型ダンジョンを舞台に鬼から逃げるトイアクション',
    descriptionKey: 'selection.miniexp.games.onigokko.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'sanpo',
    name: '散歩',
    nameKey: 'selection.miniexp.games.sanpo.name',
    entry: 'games/sanpo.js',
    version: '0.1.0',
    author: 'mod',
    description: '完全ランダムのダンジョンを散歩して歩数×1EXPを獲得する自由行動モード',
    descriptionKey: 'selection.miniexp.games.sanpo.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'darumasan',
    name: 'だるまさんがころんだ',
    nameKey: 'selection.miniexp.games.darumasan.name',
    entry: 'games/darumasan.js',
    version: '0.1.0',
    author: 'mod',
    description: '見られずにゴールすれば50EXPの緊張感ミニゲーム',
    descriptionKey: 'selection.miniexp.games.darumasan.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'acchimuitehoi',
    name: 'あっち向いてホイ',
    nameKey: 'selection.miniexp.games.acchimuitehoi.name',
    entry: 'games/acchimuitehoi.js',
    version: '0.1.0',
    author: 'mod',
    description: '攻め成功で15EXP、防御成功で5EXPを狙う反射ゲーム',
    descriptionKey: 'selection.miniexp.games.acchimuitehoi.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'janken',
    name: 'じゃんけん',
    nameKey: 'selection.miniexp.games.janken.name',
    entry: 'games/janken.js',
    version: '0.1.0',
    author: 'mod',
    description: 'クラシックじゃんけん。勝利すると10EXP',
    descriptionKey: 'selection.miniexp.games.janken.description',
    category: 'トイ',
    categories: ['トイ'],
    categoryIds: ['toy']
  },
  {
    id: 'typing',
    name: 'タイピングチャレンジ',
    nameKey: 'selection.miniexp.games.typing.name',
    entry: 'games/typing.js',
    version: '0.1.0',
    author: 'mod',
    description: '60秒タイプで正確さとスピードを競うタイピングチャレンジ',
    descriptionKey: 'selection.miniexp.games.typing.description',
    category: 'スキル',
    categories: ['スキル'],
    categoryIds: ['skill']
  },
  {
    id: 'imperial_realm',
    name: 'インペリアル・レルム',
    nameKey: 'selection.miniexp.games.imperial_realm.name',
    entry: 'games/imperial_realm.js',
    version: '0.1.0',
    author: 'mod',
    description: '村人と軍勢を指揮してウェーブ攻撃を凌ぎ敵本陣を撃破するAoE2風リアルタイムストラテジー',
    descriptionKey: 'selection.miniexp.games.imperial_realm.description',
    category: 'シミュレーション',
    categories: ['シミュレーション'],
    categoryIds: ['simulation']
  }
];
