window.__BLOCKDATA =
{
  "version": 1,
  "blocks1": [
    {
      "key": "b1004",
      "name": "朽ちた",
      "level": -4,
      "size": -1,
      "depth": -1,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1004.name"
    },
    {
      "key": "b1044",
      "name": "ネオン薄光",
      "level": -3,
      "size": -1,
      "depth": 0,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1044.name"
    },
    {
      "key": "b1051",
      "name": "ナイトTokyo",
      "level": -2,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1051.name"
    },
    {
      "key": "b1058",
      "name": "失われた広場",
      "level": -2,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1058.name"
    },
    {
      "key": "b1045",
      "name": "朽都ルインズ",
      "level": -1,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1045.name"
    },
    {
      "key": "b1052",
      "name": "新宿Backstreet",
      "level": -1,
      "size": -1,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1052.name"
    },
    {
      "key": "b1059",
      "name": "さみだれ交差点",
      "level": -1,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1059.name"
    },
    {
      "key": "b1005",
      "name": "忘却の",
      "level": 0,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1005.name"
    },
    {
      "key": "b1046",
      "name": "錆色アベニュー",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1046.name"
    },
    {
      "key": "b1053",
      "name": "渋谷の残響",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1053.name"
    },
    {
      "key": "b1060",
      "name": "Ruinの屋上",
      "level": 0,
      "size": -1,
      "depth": 0,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1060.name"
    },
    {
      "key": "b1047",
      "name": "すきまの横丁",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1047.name"
    },
    {
      "key": "b1054",
      "name": "ほこりのビル群",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1054.name"
    },
    {
      "key": "b1061",
      "name": "下北沢Alley",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1061.name"
    },
    {
      "key": "b1048",
      "name": "グレイ灰街",
      "level": 2,
      "size": -1,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1048.name"
    },
    {
      "key": "b1055",
      "name": "Rustドック",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1055.name"
    },
    {
      "key": "b1062",
      "name": "沈む工場港",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1062.name"
    },
    {
      "key": "b1049",
      "name": "雨宿りアーケード",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1049.name"
    },
    {
      "key": "b1056",
      "name": "煙る湾岸",
      "level": 3,
      "size": -1,
      "depth": 0,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1056.name"
    },
    {
      "key": "b1063",
      "name": "港区の影",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1063.name"
    },
    {
      "key": "b1024",
      "name": "こもれびの径",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "cave",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1024.name"
    },
    {
      "key": "b1029",
      "name": "朝霧ハイランド",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1029.name"
    },
    {
      "key": "b1034",
      "name": "青葉テラス",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1034.name"
    },
    {
      "key": "b1039",
      "name": "Verdant原",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1039.name"
    },
    {
      "key": "b1050",
      "name": "廃線メモリー",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1050.name"
    },
    {
      "key": "b1057",
      "name": "チルな雑居",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1057.name"
    },
    {
      "key": "b1006",
      "name": "静寂の",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1006.name"
    },
    {
      "key": "b1019",
      "name": "双影の",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1019.name"
    },
    {
      "key": "b1025",
      "name": "翠雨Meadow",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1025.name"
    },
    {
      "key": "b1030",
      "name": "風花の岬",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1030.name"
    },
    {
      "key": "b1035",
      "name": "やまなみロード",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1035.name"
    },
    {
      "key": "b1040",
      "name": "さざなみ平原",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1040.name"
    },
    {
      "key": "b1016",
      "name": "黄金の",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1016.name"
    },
    {
      "key": "b1022",
      "name": "薄暮の",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1022.name"
    },
    {
      "key": "b1026",
      "name": "朧の里",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1026.name"
    },
    {
      "key": "b1031",
      "name": "みずいろ野",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1031.name"
    },
    {
      "key": "b1036",
      "name": "フォレスト小径",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1036.name"
    },
    {
      "key": "b1041",
      "name": "鎌倉Green",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1041.name"
    },
    {
      "key": "b1084",
      "name": "水鏡ラグーン",
      "level": 6,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1084.name"
    },
    {
      "key": "b1089",
      "name": "氷雨テラス",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1089.name"
    },
    {
      "key": "b1094",
      "name": "凍土ひだまり",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1094.name"
    },
    {
      "key": "b1099",
      "name": "霧笛の埠頭",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1099.name"
    },
    {
      "key": "b1018",
      "name": "木霊する",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1018.name"
    },
    {
      "key": "b1027",
      "name": "ひなたの丘",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1027.name"
    },
    {
      "key": "b1032",
      "name": "Mossの苔庭",
      "level": 7,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1032.name"
    },
    {
      "key": "b1037",
      "name": "しずくの森",
      "level": 7,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1037.name"
    },
    {
      "key": "b1042",
      "name": "奈良の野辺",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1042.name"
    },
    {
      "key": "b1085",
      "name": "うすもや水路",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1085.name"
    },
    {
      "key": "b1090",
      "name": "ミスト渓谷",
      "level": 7,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1090.name"
    },
    {
      "key": "b1095",
      "name": "しぶきの汀",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1095.name"
    },
    {
      "key": "b1100",
      "name": "ひょうの路地",
      "level": 7,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1100.name"
    },
    {
      "key": "b1002",
      "name": "翠緑の",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1002.name"
    },
    {
      "key": "b1009",
      "name": "幽影の",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1009.name"
    },
    {
      "key": "b1017",
      "name": "紫紺の",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1017.name"
    },
    {
      "key": "b1028",
      "name": "ブリーズ渓谷",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1028.name"
    },
    {
      "key": "b1033",
      "name": "そよ風パセオ",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1033.name"
    },
    {
      "key": "b1038",
      "name": "霞む谷戸",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1038.name"
    },
    {
      "key": "b1043",
      "name": "上野の風景",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1043.name"
    },
    {
      "key": "b1086",
      "name": "霜夜バレー",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1086.name"
    },
    {
      "key": "b1091",
      "name": "雪白プロムナード",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1091.name"
    },
    {
      "key": "b1096",
      "name": "Glacial横町",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1096.name"
    },
    {
      "key": "b1012",
      "name": "月下の",
      "level": 9,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1012.name"
    },
    {
      "key": "b1087",
      "name": "アイスの洞",
      "level": 9,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1087.name"
    },
    {
      "key": "b1092",
      "name": "こおりの巣",
      "level": 9,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1092.name"
    },
    {
      "key": "b1097",
      "name": "露光の池",
      "level": 9,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1097.name"
    },
    {
      "key": "b1001",
      "name": "蒼穹の",
      "level": 10,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1001.name"
    },
    {
      "key": "b1008",
      "name": "燐光の",
      "level": 10,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1008.name"
    },
    {
      "key": "b1064",
      "name": "星明りプラットフォーム",
      "level": 10,
      "size": 1,
      "depth": 1,
      "chest": "more",
      "type": "field",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1064.name"
    },
    {
      "key": "b1073",
      "name": "蒼星テラス",
      "level": 10,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1073.name"
    },
    {
      "key": "b1082",
      "name": "ミルキー峡",
      "level": 10,
      "size": 1,
      "depth": 1,
      "chest": "more",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1082.name"
    },
    {
      "key": "b1088",
      "name": "さざ波ガーデン",
      "level": 10,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1088.name"
    },
    {
      "key": "b1093",
      "name": "フロスト街",
      "level": 10,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1093.name"
    },
    {
      "key": "b1098",
      "name": "みぞれ街道",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1098.name"
    },
    {
      "key": "b1023",
      "name": "氷雪の",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1023.name"
    },
    {
      "key": "b1065",
      "name": "天穹ドーム",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1065.name"
    },
    {
      "key": "b1074",
      "name": "オーロラ橋",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "circle-rooms",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1074.name"
    },
    {
      "key": "b1083",
      "name": "時雨Constellation",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1083.name"
    },
    {
      "key": "b1003",
      "name": "深紅の",
      "level": 12,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1003.name"
    },
    {
      "key": "b1010",
      "name": "凍てつく",
      "level": 12,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1010.name"
    },
    {
      "key": "b1020",
      "name": "聖別の",
      "level": 12,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "circle",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1020.name"
    },
    {
      "key": "b1066",
      "name": "ほしなみ回廊",
      "level": 12,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1066.name"
    },
    {
      "key": "b1075",
      "name": "つきかげ広場",
      "level": 12,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1075.name"
    },
    {
      "key": "b1021",
      "name": "呪詛の",
      "level": 35,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [
        5,
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1021.name"
    },
    {
      "key": "b1067",
      "name": "セレスティア京",
      "level": 13,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1067.name"
    },
    {
      "key": "b1076",
      "name": "Stardust路",
      "level": 13,
      "size": 1,
      "depth": 1,
      "chest": "more",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1076.name"
    },
    {
      "key": "b1014",
      "name": "嵐の",
      "level": 32,
      "size": 1,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1014.name"
    },
    {
      "key": "b1068",
      "name": "夜風オービタ",
      "level": 33,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1068.name"
    },
    {
      "key": "b1077",
      "name": "大気ステップ",
      "level": 34,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1077.name"
    },
    {
      "key": "b1007",
      "name": "咆哮する",
      "level": 29,
      "size": 1,
      "depth": 1,
      "chest": "less",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1007.name"
    },
    {
      "key": "b1069",
      "name": "Eclipseの庭",
      "level": 30,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1069.name"
    },
    {
      "key": "b1078",
      "name": "ほのぼの星屑",
      "level": 31,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1078.name"
    },
    {
      "key": "b1013",
      "name": "灼熱の",
      "level": 26,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1013.name"
    },
    {
      "key": "b1070",
      "name": "銀河バルコニー",
      "level": 27,
      "size": 1,
      "depth": 1,
      "chest": "more",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1070.name"
    },
    {
      "key": "b1079",
      "name": "Gravity坂",
      "level": 28,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1079.name"
    },
    {
      "key": "b1071",
      "name": "しじまの宙",
      "level": 24,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1071.name"
    },
    {
      "key": "b1080",
      "name": "宙港うらら",
      "level": 25,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1080.name"
    },
    {
      "key": "b1011",
      "name": "星霜の",
      "level": 19,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b1011.name"
    },
    {
      "key": "b1072",
      "name": "Nebula小町",
      "level": 22,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1072.name"
    },
    {
      "key": "b1081",
      "name": "ひかりアトリウム",
      "level": 23,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1081.name"
    },
    {
      "key": "b1015",
      "name": "奈落の",
      "level": 21,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [
        5,
        10,
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b1015.name"
    },
    {
      "key": "b1g001",
      "name": "格子の回廊",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1g001.name"
    },
    {
      "key": "b1o001",
      "name": "空の広間",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b1o001.name"
    },
    {
      "key": "b3101",
      "name": "未完成ラビリンス",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "imperfect-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3101.name"
    }
  ],
  "blocks2": [
    {
      "key": "b2002",
      "name": "錆びた",
      "level": -5,
      "size": -1,
      "depth": 0,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2002.name"
    },
    {
      "key": "b2012",
      "name": "ひび割れた",
      "level": -4,
      "size": -1,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2012.name"
    },
    {
      "key": "b2009",
      "name": "かすかな",
      "level": -3,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2009.name"
    },
    {
      "key": "b2044",
      "name": "鉄屑ヤード",
      "level": 0,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2044.name"
    },
    {
      "key": "b2049",
      "name": "油膜の床",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2049.name"
    },
    {
      "key": "b2054",
      "name": "クランク横丁",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2054.name"
    },
    {
      "key": "b2059",
      "name": "マシナリ京都",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2059.name"
    },
    {
      "key": "b2024",
      "name": "慟哭の祠",
      "level": 1,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "circle",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b2024.name"
    },
    {
      "key": "b2030",
      "name": "狂喜の広間",
      "level": 1,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2030.name"
    },
    {
      "key": "b2036",
      "name": "やすらぎの縁",
      "level": 1,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2036.name"
    },
    {
      "key": "b2042",
      "name": "怨念アトリウム",
      "level": 1,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2042.name"
    },
    {
      "key": "b2045",
      "name": "スプロケット通り",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2045.name"
    },
    {
      "key": "b2050",
      "name": "錆鉄プラットホーム",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2050.name"
    },
    {
      "key": "b2055",
      "name": "溶接アーケード",
      "level": 1,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2055.name"
    },
    {
      "key": "b2060",
      "name": "Sparkの坑",
      "level": 1,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2060.name"
    },
    {
      "key": "b2013",
      "name": "忘れられた",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2013.name"
    },
    {
      "key": "b2022",
      "name": "人知れぬ",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2022.name"
    },
    {
      "key": "b2025",
      "name": "さびしさの路",
      "level": 2,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2025.name"
    },
    {
      "key": "b2031",
      "name": "哀歌の回廊",
      "level": 2,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2031.name"
    },
    {
      "key": "b2037",
      "name": "ざわめく霊園",
      "level": 2,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2037.name"
    },
    {
      "key": "b2043",
      "name": "希望のランタン街",
      "level": 2,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2043.name"
    },
    {
      "key": "b2046",
      "name": "きしむ工廠",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2046.name"
    },
    {
      "key": "b2051",
      "name": "ギアの祠",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2051.name"
    },
    {
      "key": "b2056",
      "name": "ワイヤー橋",
      "level": 2,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2056.name"
    },
    {
      "key": "b2061",
      "name": "ピストン広場",
      "level": 2,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2061.name"
    },
    {
      "key": "b2005",
      "name": "眠れる",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2005.name"
    },
    {
      "key": "b2017",
      "name": "谺する",
      "level": 3,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2017.name"
    },
    {
      "key": "b2026",
      "name": "怒りの砦",
      "level": 3,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2026.name"
    },
    {
      "key": "b2032",
      "name": "Lonely塔",
      "level": 3,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2032.name"
    },
    {
      "key": "b2038",
      "name": "祈りのクレプス",
      "level": 3,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2038.name"
    },
    {
      "key": "b2047",
      "name": "Rustベイ",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2047.name"
    },
    {
      "key": "b2052",
      "name": "ボルトの迷路",
      "level": 3,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2052.name"
    },
    {
      "key": "b2057",
      "name": "こてさび通路",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2057.name"
    },
    {
      "key": "b2062",
      "name": "鋼の肺",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2062.name"
    },
    {
      "key": "b2064",
      "name": "風鳴りデューン",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2064.name"
    },
    {
      "key": "b2069",
      "name": "すなじの街路",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2069.name"
    },
    {
      "key": "b2074",
      "name": "ハマダーン路",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2074.name"
    },
    {
      "key": "b2079",
      "name": "カスバ小径",
      "level": 3,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2079.name"
    },
    {
      "key": "b2003",
      "name": "水没した",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2003.name"
    },
    {
      "key": "b2014",
      "name": "密やかな",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2014.name"
    },
    {
      "key": "b2020",
      "name": "灰の",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2020.name"
    },
    {
      "key": "b2027",
      "name": "憂鬱カタコンベ",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2027.name"
    },
    {
      "key": "b2033",
      "name": "Melancholy坂",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2033.name"
    },
    {
      "key": "b2039",
      "name": "しじまの墓域",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2039.name"
    },
    {
      "key": "b2048",
      "name": "歯車アベニュー",
      "level": 4,
      "size": 1,
      "depth": 0,
      "chest": "less",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2048.name"
    },
    {
      "key": "b2053",
      "name": "蒸気の小路",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2053.name"
    },
    {
      "key": "b2058",
      "name": "スモッグファクトリ",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2058.name"
    },
    {
      "key": "b2063",
      "name": "ガス灯の棟",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2063.name"
    },
    {
      "key": "b2065",
      "name": "ささやきの砂原",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2065.name"
    },
    {
      "key": "b2070",
      "name": "旋風パサージュ",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2070.name"
    },
    {
      "key": "b2075",
      "name": "Dustの双丘",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2075.name"
    },
    {
      "key": "b2080",
      "name": "奈良Sirocco",
      "level": 4,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2080.name"
    },
    {
      "key": "b2084",
      "name": "蔦絡む巣",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2084.name"
    },
    {
      "key": "b2089",
      "name": "みどりの巣穴",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [
        5
      ],
      "nameKey": "dungeon.blockdim.blocks.b2089.name"
    },
    {
      "key": "b2094",
      "name": "ひそやかな巣窟",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2094.name"
    },
    {
      "key": "b2099",
      "name": "熊笹の径",
      "level": 4,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [
        5
      ],
      "nameKey": "dungeon.blockdim.blocks.b2099.name"
    },
    {
      "key": "b2001",
      "name": "古の",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2001.name"
    },
    {
      "key": "b2010",
      "name": "緻密な",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2010.name"
    },
    {
      "key": "b2018",
      "name": "縛られた",
      "level": 5,
      "size": -1,
      "depth": 1,
      "chest": "less",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2018.name"
    },
    {
      "key": "b2028",
      "name": "悲嘆の地下室",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2028.name"
    },
    {
      "key": "b2034",
      "name": "儚いネクロポリス",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b2034.name"
    },
    {
      "key": "b2040",
      "name": "Furyの洞",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2040.name"
    },
    {
      "key": "b2066",
      "name": "音叉の谷",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2066.name"
    },
    {
      "key": "b2071",
      "name": "わずかな足跡群",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2071.name"
    },
    {
      "key": "b2076",
      "name": "からっ風の岡",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2076.name"
    },
    {
      "key": "b2081",
      "name": "風紋ギャラリー",
      "level": 5,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2081.name"
    },
    {
      "key": "b2085",
      "name": "けものみち",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2085.name"
    },
    {
      "key": "b2090",
      "name": "猛獣の檻庭",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2090.name"
    },
    {
      "key": "b2095",
      "name": "スパイク窪地",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2095.name"
    },
    {
      "key": "b2100",
      "name": "狼煙の丘",
      "level": 5,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2100.name"
    },
    {
      "key": "b2008",
      "name": "螺旋の",
      "level": 26,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2008.name"
    },
    {
      "key": "b2011",
      "name": "有棘の",
      "level": 27,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2011.name"
    },
    {
      "key": "b2016",
      "name": "灼けた",
      "level": 28,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2016.name"
    },
    {
      "key": "b2019",
      "name": "燦めく",
      "level": 29,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2019.name"
    },
    {
      "key": "b2029",
      "name": "ときめきの小径",
      "level": 30,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2029.name"
    },
    {
      "key": "b2035",
      "name": "呪縛の蔵",
      "level": 31,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2035.name"
    },
    {
      "key": "b2041",
      "name": "Calmの庭",
      "level": 32,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2041.name"
    },
    {
      "key": "b2067",
      "name": "シロッコ坂",
      "level": 33,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2067.name"
    },
    {
      "key": "b2072",
      "name": "笛吹く峡",
      "level": 34,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2072.name"
    },
    {
      "key": "b2077",
      "name": "こだまの盆地",
      "level": 35,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2077.name"
    },
    {
      "key": "b2082",
      "name": "さらさら峡谷",
      "level": 6,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2082.name"
    },
    {
      "key": "b2086",
      "name": "朽ち葉ガーデン",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2086.name"
    },
    {
      "key": "b2091",
      "name": "かげる樹海",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2091.name"
    },
    {
      "key": "b2096",
      "name": "暗獣の巣",
      "level": 6,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2096.name"
    },
    {
      "key": "b2006",
      "name": "断絶した",
      "level": 16,
      "size": -1,
      "depth": 1,
      "chest": "less",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2006.name"
    },
    {
      "key": "b2015",
      "name": "歪なる",
      "level": 17,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2015.name"
    },
    {
      "key": "b2023",
      "name": "原初の",
      "level": 18,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2023.name"
    },
    {
      "key": "b2068",
      "name": "Mirageの浜",
      "level": 19,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2068.name"
    },
    {
      "key": "b2073",
      "name": "うたかたのオアシス",
      "level": 20,
      "size": 0,
      "depth": 0,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2073.name"
    },
    {
      "key": "b2078",
      "name": "ドラムサンド",
      "level": 21,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2078.name"
    },
    {
      "key": "b2083",
      "name": "Whisper砂丘",
      "level": 22,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2083.name"
    },
    {
      "key": "b2087",
      "name": "毒霧の沼",
      "level": 23,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2087.name"
    },
    {
      "key": "b2092",
      "name": "Venom谷",
      "level": 24,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2092.name"
    },
    {
      "key": "b2097",
      "name": "霞むバイオーム",
      "level": 25,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2097.name"
    },
    {
      "key": "b2004",
      "name": "機械仕掛けの",
      "level": 11,
      "size": 1,
      "depth": 0,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2004.name"
    },
    {
      "key": "b2021",
      "name": "虚ろなる",
      "level": 12,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2021.name"
    },
    {
      "key": "b2088",
      "name": "クローの洞",
      "level": 13,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2088.name"
    },
    {
      "key": "b2093",
      "name": "さびし森",
      "level": 14,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2093.name"
    },
    {
      "key": "b2098",
      "name": "ポイズンの泉",
      "level": 15,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2098.name"
    },
    {
      "key": "b2007",
      "name": "無窮の",
      "level": 10,
      "size": 1,
      "depth": 2,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2007.name"
    },
    {
      "key": "b2g001",
      "name": "格子街路",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2g001.name"
    },
    {
      "key": "b2o001",
      "name": "大空間ホール",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b2o001.name"
    }
  ],
  "blocks3": [
    {
      "key": "b3001",
      "name": "庭園",
      "level": -5,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "single-room",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3001.name"
    },
    {
      "key": "b3003",
      "name": "迷宮",
      "level": -4,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [
        5,
        10,
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b3003.name"
    },
    {
      "key": "b3004",
      "name": "回廊",
      "level": -3,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3004.name"
    },
    {
      "key": "b3005",
      "name": "遺跡",
      "level": -2,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3005.name"
    },
    {
      "key": "b3011",
      "name": "樹海",
      "level": -1,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3011.name"
    },
    {
      "key": "b3009",
      "name": "砂海",
      "level": 1,
      "size": 1,
      "depth": 0,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3009.name"
    },
    {
      "key": "b3010",
      "name": "洞窟",
      "level": 2,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3010.name"
    },
    {
      "key": "b3022",
      "name": "浮遊島",
      "level": 3,
      "size": 1,
      "depth": 0,
      "chest": "more",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3022.name"
    },
    {
      "key": "b3085",
      "name": "地下の鼓動",
      "level": 5,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3085.name"
    },
    {
      "key": "b3090",
      "name": "ひそみの坑",
      "level": 6,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3090.name"
    },
    {
      "key": "b3095",
      "name": "ツタの横穴",
      "level": 6,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3095.name"
    },
    {
      "key": "b3100",
      "name": "ざらつく床",
      "level": 6,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3100.name"
    },
    {
      "key": "b3015",
      "name": "監獄",
      "level": 7,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3015.name"
    },
    {
      "key": "b3065",
      "name": "まぼろしの街",
      "level": 7,
      "size": 1,
      "depth": 2,
      "chest": "more",
      "type": "field",
      "bossFloors": [
        5,
        10,
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b3065.name"
    },
    {
      "key": "b3070",
      "name": "幻想パサージュ",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3070.name"
    },
    {
      "key": "b3075",
      "name": "Dreamの階",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [
        5,
        10,
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b3075.name"
    },
    {
      "key": "b3080",
      "name": "うつろいの路",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3080.name"
    },
    {
      "key": "b3086",
      "name": "きのこカタコンベ",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3086.name"
    },
    {
      "key": "b3091",
      "name": "Rootの迷路",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3091.name"
    },
    {
      "key": "b3096",
      "name": "じわりの堆",
      "level": 7,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3096.name"
    },
    {
      "key": "b3002",
      "name": "聖堂",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "wide-maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3002.name"
    },
    {
      "key": "b3008",
      "name": "研究所",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3008.name"
    },
    {
      "key": "b3013",
      "name": "祭壇",
      "level": 8,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "rooms",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3013.name"
    },
    {
      "key": "b3021",
      "name": "境界域",
      "level": 8,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3021.name"
    },
    {
      "key": "b3045",
      "name": "雪灯の野",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3045.name"
    },
    {
      "key": "b3050",
      "name": "Frost京",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3050.name"
    },
    {
      "key": "b3055",
      "name": "北極光テラス",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3055.name"
    },
    {
      "key": "b3060",
      "name": "ツンドラ横町",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3060.name"
    },
    {
      "key": "b3066",
      "name": "夢見のプロムナード",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3066.name"
    },
    {
      "key": "b3071",
      "name": "Illusion丘",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3071.name"
    },
    {
      "key": "b3076",
      "name": "ふわりの小町",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3076.name"
    },
    {
      "key": "b3081",
      "name": "異邦アーケード",
      "level": 8,
      "size": 1,
      "depth": 2,
      "chest": "more",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3081.name"
    },
    {
      "key": "b3087",
      "name": "胞子の回廊",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3087.name"
    },
    {
      "key": "b3092",
      "name": "暗渠の川辺",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3092.name"
    },
    {
      "key": "b3097",
      "name": "コロニーの隙",
      "level": 8,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3097.name"
    },
    {
      "key": "b3012",
      "name": "地下墓地",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "single-room",
      "bossFloors": [
        5,
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3012.name"
    },
    {
      "key": "b3018",
      "name": "氷窟",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3018.name"
    },
    {
      "key": "b3025",
      "name": "王都アーケイディア",
      "level": 9,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "rooms",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3025.name"
    },
    {
      "key": "b3032",
      "name": "Temple小径",
      "level": 9,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3032.name"
    },
    {
      "key": "b3039",
      "name": "Ruinsの中庭",
      "level": 9,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3039.name"
    },
    {
      "key": "b3046",
      "name": "白氷の窪地",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3046.name"
    },
    {
      "key": "b3051",
      "name": "氷霞の路",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3051.name"
    },
    {
      "key": "b3056",
      "name": "アイシクルの庭",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3056.name"
    },
    {
      "key": "b3061",
      "name": "寒月の辻",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3061.name"
    },
    {
      "key": "b3067",
      "name": "フェイブル回廊",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3067.name"
    },
    {
      "key": "b3072",
      "name": "白昼夢テラス",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3072.name"
    },
    {
      "key": "b3077",
      "name": "影絵の館",
      "level": 9,
      "size": 1,
      "depth": 2,
      "chest": "more",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3077.name"
    },
    {
      "key": "b3082",
      "name": "イマジナリ京都",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3082.name"
    },
    {
      "key": "b3088",
      "name": "マイセリア庭",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3088.name"
    },
    {
      "key": "b3093",
      "name": "朽ち縄の井戸",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3093.name"
    },
    {
      "key": "b3098",
      "name": "Sporeの街",
      "level": 9,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3098.name"
    },
    {
      "key": "b3006",
      "name": "城砦",
      "level": 10,
      "size": 1,
      "depth": 1,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3006.name"
    },
    {
      "key": "b3014",
      "name": "神殿",
      "level": 10,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3014.name"
    },
    {
      "key": "b3020",
      "name": "闘技場",
      "level": 10,
      "size": 0,
      "depth": 0,
      "chest": "more",
      "type": "maze",
      "bossFloors": [
        5,
        10,
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b3020.name"
    },
    {
      "key": "b3026",
      "name": "いにしえの柱廊",
      "level": 10,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3026.name"
    },
    {
      "key": "b3033",
      "name": "礎のドーム",
      "level": 10,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3033.name"
    },
    {
      "key": "b3040",
      "name": "伽藍の回向",
      "level": 10,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "narrow-maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3040.name"
    },
    {
      "key": "b3047",
      "name": "こごえる街路",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3047.name"
    },
    {
      "key": "b3052",
      "name": "ミルク色の平原",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3052.name"
    },
    {
      "key": "b3057",
      "name": "霧氷ハーバー",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3057.name"
    },
    {
      "key": "b3062",
      "name": "ふぶきの峰",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3062.name"
    },
    {
      "key": "b3068",
      "name": "フィクションの庭",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3068.name"
    },
    {
      "key": "b3073",
      "name": "うつつの割れ目",
      "level": 10,
      "size": 1,
      "depth": 2,
      "chest": "more",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3073.name"
    },
    {
      "key": "b3078",
      "name": "さざめく世界端",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3078.name"
    },
    {
      "key": "b3083",
      "name": "Mirageの街角",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3083.name"
    },
    {
      "key": "b3089",
      "name": "脈打つ洞",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3089.name"
    },
    {
      "key": "b3094",
      "name": "菌糸の広間",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3094.name"
    },
    {
      "key": "b3099",
      "name": "地下街アンダー",
      "level": 10,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3099.name"
    },
    {
      "key": "b3016",
      "name": "機械塔",
      "level": 11,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3016.name"
    },
    {
      "key": "b3027",
      "name": "レリクス石庭",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3027.name"
    },
    {
      "key": "b3034",
      "name": "祈祷のテラス",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3034.name"
    },
    {
      "key": "b3041",
      "name": "石畳プロムナード",
      "level": 11,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3041.name"
    },
    {
      "key": "b3048",
      "name": "オーロラの丘",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3048.name"
    },
    {
      "key": "b3053",
      "name": "吹雪の回廊",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3053.name"
    },
    {
      "key": "b3058",
      "name": "セイバン雪脈",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3058.name"
    },
    {
      "key": "b3063",
      "name": "しらゆきの里",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3063.name"
    },
    {
      "key": "b3069",
      "name": "ねむり雲",
      "level": 11,
      "size": 1,
      "depth": 2,
      "chest": "more",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3069.name"
    },
    {
      "key": "b3074",
      "name": "虚実の塔",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3074.name"
    },
    {
      "key": "b3079",
      "name": "きらめく泡沫",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3079.name"
    },
    {
      "key": "b3084",
      "name": "まどろみの凹室",
      "level": 11,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "snake",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3084.name"
    },
    {
      "key": "b3007",
      "name": "廃都",
      "level": 26,
      "size": 1,
      "depth": 1,
      "chest": "normal",
      "type": "circle",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3007.name"
    },
    {
      "key": "b3017",
      "name": "要塞",
      "level": 27,
      "size": 1,
      "depth": 1,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3017.name"
    },
    {
      "key": "b3023",
      "name": "聖域",
      "level": 28,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "grid",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3023.name"
    },
    {
      "key": "b3028",
      "name": "祭壇の間",
      "level": 29,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3028.name"
    },
    {
      "key": "b3035",
      "name": "古代のオベリスク",
      "level": 30,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "field",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3035.name"
    },
    {
      "key": "b3042",
      "name": "正殿の階",
      "level": 31,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3042.name"
    },
    {
      "key": "b3049",
      "name": "霜星の峡",
      "level": 32,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3049.name"
    },
    {
      "key": "b3054",
      "name": "しずかな氷穴",
      "level": 33,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3054.name"
    },
    {
      "key": "b3059",
      "name": "Gelidの湾",
      "level": 34,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "narrow-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3059.name"
    },
    {
      "key": "b3064",
      "name": "Aurora橋上",
      "level": 35,
      "size": 0,
      "depth": 2,
      "chest": "normal",
      "type": "field",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3064.name"
    },
    {
      "key": "b3019",
      "name": "火山窟",
      "level": 22,
      "size": 0,
      "depth": 1,
      "chest": "less",
      "type": "wide-maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3019.name"
    },
    {
      "key": "b3029",
      "name": "聖塔の回廊",
      "level": 23,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3029.name"
    },
    {
      "key": "b3036",
      "name": "きよき大路",
      "level": 24,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3036.name"
    },
    {
      "key": "b3043",
      "name": "古城の翼廊",
      "level": 25,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "open-space",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3043.name"
    },
    {
      "key": "b3030",
      "name": "奈良神苑",
      "level": 19,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "open-space",
      "bossFloors": [
        10
      ],
      "nameKey": "dungeon.blockdim.blocks.b3030.name"
    },
    {
      "key": "b3037",
      "name": "アーカイブの庫",
      "level": 20,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "circle-rooms",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3037.name"
    },
    {
      "key": "b3044",
      "name": "聖都Galleria",
      "level": 21,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3044.name"
    },
    {
      "key": "b3024",
      "name": "裂け目",
      "level": 16,
      "size": 0,
      "depth": 2,
      "chest": "less",
      "type": "rooms",
      "bossFloors": [
        15
      ],
      "nameKey": "dungeon.blockdim.blocks.b3024.name"
    },
    {
      "key": "b3031",
      "name": "祠宮の庭",
      "level": 17,
      "size": 0,
      "depth": 1,
      "chest": "more",
      "type": "maze",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3031.name"
    },
    {
      "key": "b3038",
      "name": "朱雀門プラザ",
      "level": 18,
      "size": 0,
      "depth": 1,
      "chest": "normal",
      "type": "single-room",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3038.name"
    },
    {
      "key": "b3g001",
      "name": "グリッド回廊",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "cave",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3g001.name"
    },
    {
      "key": "b3o001",
      "name": "虚空の広間",
      "level": 0,
      "size": 0,
      "depth": 0,
      "chest": "normal",
      "type": "grid",
      "bossFloors": [],
      "nameKey": "dungeon.blockdim.blocks.b3o001.name"
    }
  ]
};
